import Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :mindful, MindfulWeb.Endpoint,
  # url: [scheme: "https", host: "mindful.care", port: 443],
  # force_ssl: [rewrite_on: [:x_forwarded_proto]],
  http: [ip: {127, 0, 0, 1}, port: 4000],
  cache_static_manifest: "priv/static/cache_manifest.json"

# Do not print debug messages in production
config :logger, level: :info

# Environment variable for conditional code based on environment
config :mindful, :environment, :prod

# config :sentry,
#   dsn: "https://840971b82c9343ffbdc05b53d7a262bb@o1102072.ingest.sentry.io/6128230",
#   environment_name: :prod,
#   enable_source_code_context: true,
#   root_source_code_path: File.cwd!(),
#   tags: %{
#     env: "production"
#   },
#   included_environments: [:prod]
